### ISSUE TITLE
/rc register only works once on the proxy.

### ISSUE THREAD

**Issue by TheDeafCreeper** [Aelysium-Group/rusty-connector#10] opened 2023-06-03 02:49 UTC
When running `/rc register all` or `/rc register family FAMILY` it'll only register missing families the first time it's run. Any subsequent runs don't do anything.

Console:
```
> rc register family woolsacre-game
[22:38:53 INFO]: RustyConnector:
[Velocity](127.0.0.1) |>~=- woolsacre-game
[22:38:53 ERROR] [rustyconnector-velocity]: An incoming message was thrown away!
[22:38:53 INFO] [rustyconnector-velocity]: To view the thrown away message use: /rc message get 1113597498787643392
```
(Thrown away message is from the proxy)

Servers also have nothing in the console.

**Comment by nathan-i-martin** [comment] 2023-06-03 03:19
The root cause of this issue is a duplicate of https://github.com/Aelysium-Group/rusty-connector/issues/11

**Closed by nathan-i-martin** 2023-06-03 03:19 UTC
Labels: bug, duplicate
